#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if index .Values "eric-oss-assurance-augmentation-db" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eric-assurance-augmentation.name" . }}-db-secret
  labels:
  {{- include "eric-assurance-augmentation.kubernetes-io-info" . | nindent 4 }}
  annotations:
  {{- include "eric-assurance-augmentation.helm-annotations" . | indent 4 }}
type: Opaque
data:
  # For custom user and password
  pguserid: {{ "auguser" | b64enc | quote }}
  pgpasswd: {{ "Custom!Pwd123" | b64enc | quote }}

  # For super user and password
  super-user: {{ "postgresuser" | b64enc | quote }}
  super-pwd: {{ "Post!Gres123" | b64enc | quote }}

  # For metrics user and password
  metrics-user: {{ "exporteruser" | b64enc | quote }}
  metrics-pwd: {{ "Exporter123!" | b64enc | quote }}

  # For replica user and password
  replica-user: {{ "replicauser" | b64enc | quote }}
  replica-pwd: {{ "Replica1234!" | b64enc | quote }}
{{- end -}}