# #
# # COPYRIGHT Ericsson 2022
# #
# #
# #
# # The copyright to the computer program(s) herein is the property of
# #
# # Ericsson Inc. The programs may be used and/or copied only with written
# #
# # permission from Ericsson Inc. or in accordance with the terms and
# #
# # conditions stipulated in the agreement/contract under which the
# #
# # program(s) have been supplied.
# #
{{- if .Values.global.networkPolicy }}
{{- if .Values.global.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-assurance-augmentation.name" . }}-assurance-augmentation-ingress-policy
  labels:
    {{- include "eric-assurance-augmentation.labels" .| nindent 4 }}
  annotations:
    {{- include "eric-assurance-augmentation.helm-annotations" .| nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-assurance-augmentation
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector: {}
{{- end }}
{{- end }}